social_adresse:
    path:     /
    defaults: { _controller: "EquipeBundle:Social:index" }

social_adresse_show:
    path:     /{id}/show
    defaults: { _controller: "EquipeBundle:Social:show" }

social_adresse_new:
    path:     /new
    defaults: { _controller: "EquipeBundle:Social:new" }

social_adresse_create:
    path:     /create
    defaults: { _controller: "EquipeBundle:Social:create" }
    methods:  POST

social_adresse_edit:
    path:     /{id}/edit
    defaults: { _controller: "EquipeBundle:Social:edit" }

social_adresse_update:
    path:     /{id}/update
    defaults: { _controller: "EquipeBundle:Social:update" }
    methods:  [POST, PUT]

social_adresse_delete:
    path:     /{id}/delete
    defaults: { _controller: "EquipeBundle:Social:delete" }
    methods:  [POST, DELETE]
