<?php

namespace CMS\EquipeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesRepository extends EntityRepository
{

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getEquipeInformations()
    {
        $qb = $this->createQueryBuilder("e");
        $qb->innerJoin('e.galleries', 'image');
        $qb->innerJoin('e.adresses', 'adresse');
        $qb->innerJoin('e.socials', 'social');
        $qb->orderBy('e.nom', 'ASC');
        return $qb;
     }
}
